/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package halveringstid;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
/**
 *
 * @author isawe04
 */
public class JPanelHalveringstid extends javax.swing.JPanel {
    ArrayList<Integer> graf = new ArrayList<>();
    int vikt;
    int halveringstid;
    int tid;
    int y;

    
    public JPanelHalveringstid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        btnGraf = new javax.swing.JButton();
        TxfTid = new javax.swing.JTextField();
        TxfHalveringstid = new javax.swing.JTextField();
        TxfVikt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        btnGraf.setText("Skapa graf");
        btnGraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafActionPerformed(evt);
            }
        });

        TxfTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfTidActionPerformed(evt);
            }
        });

        TxfHalveringstid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfHalveringstidActionPerformed(evt);
            }
        });

        TxfVikt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfViktActionPerformed(evt);
            }
        });

        jLabel1.setText("Ämne vikt (g)");

        jLabel2.setText("Halveringstid");

        jLabel3.setText("Tid (år)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(TxfVikt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxfTid)
                            .addComponent(TxfHalveringstid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112)
                .addComponent(btnGraf)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxfVikt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxfHalveringstid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxfTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxfViktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfViktActionPerformed

    }//GEN-LAST:event_TxfViktActionPerformed

    private void TxfHalveringstidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfHalveringstidActionPerformed

    }//GEN-LAST:event_TxfHalveringstidActionPerformed

    private void TxfTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfTidActionPerformed

    }//GEN-LAST:event_TxfTidActionPerformed

    private void btnGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafActionPerformed
        graf.clear();
        vikt = Integer.parseInt(TxfVikt.getText());
        halveringstid = Integer.parseInt(TxfHalveringstid.getText());
        tid = Integer.parseInt(TxfTid.getText());
        for (int i = 1; i <= tid; i++) {
            y = (int) (vikt * Math.pow(0.5, (double) i / halveringstid));
            if(y >= 0 && y <= 100 && graf.size() < 300){
                graf.add(y);
            }
        }
        repaint();
    }//GEN-LAST:event_btnGrafActionPerformed

    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.fillRect(40, 150, 1, 100);
        g.fillRect(40, 250, 300, 1);
        g.fillRect(12, 150, 28, 1);
        g.setFont(new Font("TimesRoman", Font.PLAIN, 10));
        g.drawString("(g)", 35, 145);
        g.drawString("100", 12, 148);
        System.out.println(graf);
        for (int i = 0; i < graf.size(); i++) {
            g.fillRect(40+i, 250-graf.get(i), 2, 2);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxfHalveringstid;
    private javax.swing.JTextField TxfTid;
    private javax.swing.JTextField TxfVikt;
    private javax.swing.JButton btnGraf;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
